### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by miroshar-success** [OskarMast/CMBListini#1]
This project is MVC ASP.NET project.
On Controller side, how to get data from database?

**Comment by dancerking** [comment]
You can use follow code method.
var Alesaggio = dbCtx.L6020_2Alesaggio.Where(x => x.AlesaggioisActive).Where(x => x.AlesaggioSerieID == Serie.SerieID).Where(x => x.AlesaggioLength == al).FirstOrDefault();

**Comment by miroshar-success** [comment]
okay. It works well.
One more question.
How to resolve RegExp?

**Comment by dancerking** [comment]
Yeah, you should use RegExp.
/^(\w{2})(\d{3})([a-zA-Z])(\d{4})([a-zA-Z])([w-z]{0,2})(\d{2})/
Please let you try.

**Comment by miroshar-success** [comment]
Oh, Perfect.
All work well.
